spring.application.name=client
server.port=8080
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090
spring.security.oauth2.client.registration.spring.provider=spring
spring.security.oauth2.client.registration.spring.client-id=spring
spring.security.oauth2.client.registration.spring.client-secret=spring
spring.security.oauth2.client.registration.spring.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spring.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.spring.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.spring.scope=openid,profile

spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8081
spring.ai.mcp.client.initialized=false

spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY:ollama}
spring.ai.openai.base-url=${SPRING_AI_OPENAI_BASE_URL:http://localhost:11434/v1}
spring.ai.openai.chat.options.model=${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL:llama3.2}